### ISSUE TITLE
Student registration with access protection?

### ISSUE THREAD

**Issue by exploide** [d120/pyophase#10]
At the moment, the student registration page is publicly accessible when registration process is enabled. The old system required tutor login credentials. Should we require authentication for this?

@bhaettasch thoughts??

**Comment by jlauinger** [comment]
I would do authentication, seems more reasonable to me... Imagine the tons of fake data in case a student (may or may not be under the influence of alcohol) finds out how to insert stuff :spaghetti:

**Comment by bhaettasch** [comment]
Maybe it's enough to restrict the access to a specific IP-Range and allow adding only in a smal time window (during group slots)?

**Comment by ckleemann** [comment]
Do we have to handle this in pyOphase itself? I think it is a case of operational security and thus should be handled by settings of the deployment e.g. restrictions in Apache HTTPD

**Comment by exploide** [comment]
I implemented the protection as a simple login_required. Then we can have a general Tutor account for that purpose.

Restricting access to a specific IP range seems a bit too hacky and not very robust for me.

Personally, I don't like putting this in Apache config. Should work by itself in the intended manner.

**Comment by ckleemann** [comment]
Now it is not possible to logout from such account. A view for a logout dose not exist. A link in the registration view is also missing.

Second: "[The login_required decorator does NOT check the is_active flag on a user.] (https://docs.djangoproject.com/en/1.8/topics/auth/default/#the-login-required-decorator)" Hence it might be a good idea to add also a custom permission in Students.Student model for the view or to check the user against Students.Student.create permission for the view. This also solves the problem if there would be accounts in the future which should not be able to access the view.
