### ISSUE TITLE
Enforce standard format for phone numbers

### ISSUE THREAD

**Issue by jlauinger** [d120/pyophase#108]
Use a library to automatically convert phone numbers on staff register, e.g. `+40 (0) 1234 8858852`.

[daviddrysdale/python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers)

**Comment by exploide** [comment]
Maybe this comes in handy

https://github.com/stefanfoulis/django-phonenumber-field

**Comment by ckleemann** [comment]
After having a closer look at django-phonenumber-field it seams like some of the functionality is not as I would expect.
For example: Search by a phone number in Django Admin dose not work anymore.

Also what I want to have is some representation: If the number has the default region prefix use the national representation else use the international representation.
But the international representation always displays the prefix and the national never displays any prefix.

I guess some work on upstream would be required.
