### ISSUE TITLE
Missing translations for website app

### ISSUE THREAD

**Issue by Miterion** [d120/pyophase#128]

**Comment by bhaettasch** [comment]
There are still some translations missing. Should be changed soon as this is the main entry point for visitors (who need translations).

**Comment by bhaettasch** [comment]
All strings without english representation have been translated with 5f9324d and a few more hardcoded strings were replaced with translated versions. Nevertheless, one should check that there are no hardcoded strings anymore before closing this issue.

**Comment by Miterion** [comment]
As we are about to remove the website app in #263 I think this issue can be closed.
