### ISSUE TITLE
Deactivate CodeClimate Checks for Migrations

### ISSUE THREAD

**Issue by bhaettasch** [d120/pyophase#130]
As migrations are auto-generated, they often produce code climate warnings. Is it possible to exclude the migration files from CodeClimate checks?

**Comment by bhaettasch** [comment]
I just saw that there is already a rule with that aim in the configuration file -- nevertheless it is obviously not working...

**Comment by jlauinger** [comment]
I simply deactivated CodeClimate, hugely overrated, sad. Make pyOphase pull requests buildable again!
