### ISSUE TITLE
Clean up website models

### ISSUE THREAD

**Issue by schroedingersZombie** [d120/pyophase#143]
In the Oinforz and Schedule models of the website app a field 'degree' is used which is redundant to the new introduced OphaseCategories.
So I think we should replace the 'degree' fields.
I currently see three options:

1. Replace all 'degree' fields with OneToOne relationships to OphaseCategories (this is the easiest solution I have implemented  this for the Schedule as itermediate solution)
2. Merge data in models identified by 'degree' in the OphaseCategories model (I think this is bad because ophasebase must store data that belongst to website)
3. In the website app extend the OphaseCategories model and put the fields of Oinforz and Schedule in there (I think this is the cleanest solution)

I prefer option 3 but would like to get some feedback from others who work on this project for a longer time.

**Comment by bhaettasch** [comment]
Resolved with #144
