### ISSUE TITLE
Student mail export

### ISSUE THREAD

**Issue by exploide** [d120/pyophase#16]
There should be an admin action to export the Student's mail addresses for mass subscription, similar to the functionality implemented for Staff. This depends on #7

**Comment by exploide** [comment]
Milestone due date is coming. You have to do with #7 and #19. 

If you don't have enough time, I can take this one after #7 is closed.

**Comment by bhaettasch** [comment]
Now that #7 is closed, I will take charge of this one...

**Comment by bhaettasch** [comment]
Closed by dd9cef7, implemented as dashboard view.
