### ISSUE TITLE
Link to Aufgabenbeschreibung not interpreted as HTML

### ISSUE THREAD

**Issue by exploide** [d120/pyophase#17]
On the staff registration page, the Aufgabenbeschreibung links are not interpreted as HTML since the last Django update. <a href... gets printed on the page.

**Comment by exploide** [comment]
nope, does not work for me :stuck_out_tongue:

**Comment by ckleemann** [comment]
Yes my testing was not right. So I fixed the bug finally and wrote a TestCase. 
Remember: 
* String += SafeText == String.
* SafeText += SafeText == SafeText.
