### ISSUE TITLE
Helper overview

### ISSUE THREAD

**Issue by exploide** [d120/pyophase#18]
Helferorga needs kind of an overview of the people which want to help out during certain activities. Something which is helpful during the arrangement.

It is not definitely clear yet how it should look like.

**Comment by exploide** [comment]
Now that there is #27, I have no idea if additional functionality is necessary.

@chriswars: tell me if you need more and how urgent it is. Maybe we know more after the upcoming Ophase.

Then, I can finally close this ticket. :P

**Comment by chriswars** [comment]
I think the helpermatrix fulfills the demands. More overview-functionality isn't necessary :)

**Comment by exploide** [comment]
Ok, I will close this for now. If it turns out that helferorga needs more functionality, simply open a new issue.
