### ISSUE TITLE
Introducing a ophase proxy model for student model

### ISSUE THREAD

**Issue by ckleemann** [d120/pyophase#186]
At the moment each instance of a Student object is linked to the Ophase object it belongs to. It has shown that the solution "link all objects that need to drop to one object" dose not work properly. 
Data from staff need to be stored longer then the students etc. As result all personal data is stored until the last personal data is not need anymore.

To avoid this problem for personal data of students, a new model should be introduced to allow to drop only all student data by deleting this object. To foreign key relation would be as the following:
```
Student Instance -> Student Ophase Proxy Instance -> Ophase Instance
```
This solution still allows to drop all data by deleting the Ophase instance but introduces a shortcut to delete only all student data by deleting the Student Ophase proxy instance. This gives a better data privacy to the students as it was initial proposed. See the section Data Privacy in the projects readme.

Note: All Objects should be linked by a foreign key relation. There is no need for a [Django Proxy Model](https://docs.djangoproject.com/en/1.11/topics/db/models/#proxy-models)

**Comment by bhaettasch** [comment]
How about creating a view or (admin) action to delete all students of a given ophase instead of changing the model?

**Comment by ckleemann** [comment]
This already exists: Filter Student objects by Ophase, select all, click delete and confirm. It is not used at all.

**Comment by bhaettasch** [comment]
So your proposal is absolutely useless since the new model requires the same steps to take (manual action by the responsible persons). You are trying to solve social issues with a technical solution.

**Comment by ckleemann** [comment]
I took look on the system. The solution form my last comment dose not exist.

**Comment by bhaettasch** [comment]
OK, I had a look at it. Deleting freshmen without deleting the whole ophase object can be done on multiple ways -- directly after the ophase by simply deleting all entries or by deleting all of their tutor groups (foreign key to tutor group cannot be NULL and deletion behaviour is set to CASCADE).

This can be done with three or four clicks, hence I don't think we have to include additional complexity here (which will need the same effort to be used). I am closing this as wontfix.
