### ISSUE TITLE
Introduce Dashboard

### ISSUE THREAD

**Issue by bhaettasch** [d120/pyophase#20]
Create a dashboard for all users which do normally not really work with backend models but need lightweight information and special actions (which do not fit into the concept of admin_actions).

The dashboard should display information and offer an easy way to access special actions. It has to make sure, that only logged in persons with the right permission have access to the actions and information they really need.

The widgets and pages of the dashboard should be implemented as part of the app they deal with, using common functions and classes from the dashboard. The dashboard component itself checks permissions and aggregates information.

**Comment by bhaettasch** [comment]
Examples:
- [ ] Exam assignment
- [ ] Show current tutor/helper/orga count
- [ ] Show current participant stats
- [ ] Several status information used by helpdesk

**Comment by exploide** [comment]
For rendering widgets, we could simply use a small template and call its render_to_string method in the widget's render method. Maybe wrap it as SafeText when necessary. Then it can be included in the main dashboard template.

For whole-page dashboard components, it might be good using ordinary views?!

**Comment by bhaettasch** [comment]
See branch dashboard (42a0314, b1bbe4b, 33e088c) for current developement state.

**Comment by bhaettasch** [comment]
![dashboard_widgets](https://cloud.githubusercontent.com/assets/6319964/9699625/55d9c25c-53ea-11e5-95d8-52378b9c861c.png)

**Comment by bhaettasch** [comment]
With commit  33e088c also big views are protected by permission handling. 

The files are addressed by a special dashboard_urls.py file which has to be indluded in dashboard for every supported app.

If an app contains a lot of dashboard widgets and views, it might be wise to split up the dashboard_components.py file into dashboard_views.py and dashboard_widgets.py.

**Comment by bhaettasch** [comment]
The general software design was introduced with merging #29. Not all examples mentioned above are already implemented, but since they are only examples and the actual feature is already implemented, this issue can be closed now.
