### ISSUE TITLE
Set display name for outgoing mails

### ISSUE THREAD

**Issue by jnhmn** [d120/pyophase#202]
Outgoing mails should have a display Name in the FROM field and not only the sender address

**Comment by Miterion** [comment]
Changing this [line](https://github.com/d120/pyophase/blob/dfeecfdb7edaa360a3694dc891edca5de6025544/pyophase/settings_production.py#L41) should do it. I would suggest to use `<pyophase> pyophase@fachschaft.informatik.tu-darmstadt.de`

**Comment by ckleemann** [comment]
@miterion it is ```pyophase <pyophase@fachschaft.informatik.tu-darmstadt.de>``` fix is in master
