### ISSUE TITLE
Depecrecated usage of django.core.urlresolvers

### ISSUE THREAD

**Issue by Miterion** [d120/pyophase#206]
Current builds fail with future versions of django.

**Comment by ckleemann** [comment]
Build are passed now. But pyTUID is still having an old import. Therefore Django 2.0.1 currently fails in production. I created a pull request for pyTUID to fix the old import (https://github.com/d120/pyTUID/pull/14).

**Comment by ckleemann** [comment]
eb9cfe02c9d53d5c5db1f5398ba5b9aac2e1b526 fixes this issue
