### ISSUE TITLE
Use LDAP for admin/orga-authentification

### ISSUE THREAD

**Issue by bhaettasch** [d120/pyophase#228]
Instead of managing different user accounts for pyOphase and other FS and ophase systems, we should use the accounts provided by the LDAP server. Currently, there are special accounts for the special jobs -- in the future, the rights for each job should be assigned to groups (Edit: django user groups, not ldap groups) which than can be assigned to the persons with that job by the heads of ophase.

This can proably be done analogous to the recent changes in pyOfahrt: https://github.com/d120/pyofahrt/commit/25bd9313de16a477a01560ae250e648f9362cc36

**Comment by bhaettasch** [comment]
Clarification: I suggest to use the ldap groups ophase and ophase-leitung to check who is allowed to login (those are the persons that are also allowed to access the ophase trac). The remaining rights should depend on django groups, not be modelled in the ldap.

**Comment by ckleemann** [comment]
fixed with #324.
