### ISSUE TITLE
download triggered on page load

### ISSUE THREAD

**Issue by jlauinger** [d120/pyophase#24]
Sometimes a download begins instead of the requested page being shown.

Could be a deployment problem.

**Comment by exploide** [comment]
Looks similar to #25 
HTTP header preceded with null byte or something like that.

**Comment by exploide** [comment]
Deployment problem. Seems to be triggered in Chrome caused by HTTP keepalive.

Adding the following line to Apache config seems to fix the issue. Maybe not the best solution but I haven't found a better solution, yet.
`SetEnvIf Request_URI /ophasehq/ nokeepalive`
