### ISSUE TITLE
"Orga-Übersicht anzeigen"

### ISSUE THREAD

**Issue by GeneralGeki** [d120/pyophase#245]
Wirft mit dem aktuellen staff 500

**Comment by ckleemann** [comment]
Meinst du die Admin Aktion "Orga-Übersicht anzeigen" in admin -> Staff -> Person ?

**Comment by GeneralGeki** [comment]
Wahrscheinlich ja :D (bin mir nicht mehr sicher)
Die von dir beschriebene Aktion wirft auf jedenfall bei mir nen 500

**Comment by ckleemann** [comment]
Ich bin da auch drüber gestolpert. Code ohne Testfälle tendiert dazu irgendwann kaputt zu gehen wenn umgebaut wird. 🤷🏻‍♂️

Ich schreib mir das mal auf die Todo Liste. Ich denke das in einer Admin Aktion zu verstecken ist sowieso nicht die beste Idee. Im Dashboard wäre das wohl besser aufgehoben.
