### ISSUE TITLE
CSS files fail to load

### ISSUE THREAD

**Issue by jlauinger** [d120/pyophase#25]
Sometimes no CSS files will load and the OphaseHQ will look disturbing.

related to #24?

**Comment by exploide** [comment]
Under certain (yet unclear) conditions (Chrome?!), base.css contains garbage in front of the HTTP header. This leads to malformed responses which are not interpreted by the browser.

**Comment by exploide** [comment]
Not reproducible with dev server. Seems to be a deployment issue.

Same as #24

**Comment by exploide** [comment]
Deployment problem. Seems to be triggered in Chrome caused by HTTP keepalive.

Adding the following line to Apache config seems to fix the issue. Maybe not the best solution but I haven't found a better solution, yet.
`SetEnvIf Request_URI /ophasehq/ nokeepalive`
