### ISSUE TITLE
empty actions drop down list

### ISSUE THREAD

**Issue by jlauinger** [d120/pyophase#26]
At least (sometimes?) for me, there are no actions available in actions drop down lists. Example screenshot provided.

related to #24?

![ophasehq-bug](https://cloud.githubusercontent.com/assets/1872086/9674289/52cecf8a-52af-11e5-850b-6ea1a06f99bb.png)

**Comment by exploide** [comment]
Deployment problem. Seems to be triggered in Chrome caused by HTTP keepalive.

Adding the following line to Apache config seems to fix the issue. Maybe not the best solution but I haven't found a better solution, yet.
`SetEnvIf Request_URI /ophasehq/ nokeepalive`
