### ISSUE TITLE
List index out of range while generating an exam assignement

### ISSUE THREAD

**Issue by Miterion** [d120/pyophase#268]
When generating an exam assignment and choosing the option "Few rooms as possible" a 500 Server Error gets thrown with the following description:
```
IndexError at /dashboard/exam/assignment/new/
list index out of range
```

**Comment by ckleemann** [comment]
Could you provide some more information regarding the error? Otherwise it would be hard to find the bug. As the exam App dose not have any testcases yet it this bug would be a good starting point for writing some unittests.

**Comment by Miterion** [comment]
![](https://i.imgur.com/6vCn2sM.jpg) These are the chosen settings for this error to be thrown. A stack trace was send to all pyophase developers.

**Comment by ckleemann** [comment]
Oh this tries to arrange 400 Persons but there are only 372 seats available in this configuration. I guess there is no check if enough seats are available before doing the assignment.
