### ISSUE TITLE
remember group when adding students at /teilnehmer

### ISSUE THREAD

**Issue by jlauinger** [d120/pyophase#32]
It is currently required to select the tutor group for each and every student added. Here are two possibilities to greatly improve UX, of which I personally would prefer the second:

 * introduce some kind of session state to pre-select or leave selected the tutor group, so that consecutive adding of students of the same group is much faster
 * select the tutor group of the last added entry in this session by default on page load, which effectively provides the same results while being much more transparent and non-invasive

As the workflow will probably be a tutor providing a pool PC to his group's students for them to fill in their names, having the group be selected automatically would save a lot of time.

**Comment by ckleemann** [comment]
The implementation is using the second possibility.
