### ISSUE TITLE
Display newsletter counts in registration dashboard

### ISSUE THREAD

**Issue by bhaettasch** [d120/pyophase#36]
When there was only one newsletter, the count of future followers was displayed in dashboard. This was removed when multiple newslettes were introduced, but it would be nice to add something similar again with an appropriate representation.

**Comment by bhaettasch** [comment]
Instead of showing the newsletter subscription counts per group in registration table, there is now a special overview page, showing the counts per newsletter, which makes far more sense. Thus dd9cef7 probably closes this issue, but please review prior to closing this one.

**Comment by exploide** [comment]
Looks good. Must be sufficient for tomorrow. Maybe we can think if it's reasonable to only show Students from current Ophase. But there are probably other parts of the code which needs refactored for this case. Not sure at the moment.

**Comment by bhaettasch** [comment]
I thought all the freshmen should be deleted after the ophase (by deleting the ophase object) or at least before a new one is created. Thus only the students from the current ophase will be shown without any changes, won't they?

**Comment by exploide** [comment]
SHOULD but not MUST. Don't think we can rely on this.

**Comment by bhaettasch** [comment]
Then we should add a convenience function to restrict the list of student objects to those of the current ophase. I opened a new issue (#39) for that so we can discuss and keep track.
