### ISSUE TITLE
Dashboard: "Tage" vs "Tag"

### ISSUE THREAD

**Issue by jlauinger** [d120/pyophase#38]
When only 1 day is left until the Ophase, the "Ophasenstatus" widget in the dashboard should read "1 Tag [...]" instead of "1 Tage [...]".

I'm wondering whether it will start showing negative remaining time starting tomorrow :D

**Comment by exploide** [comment]
No it won't -.-

But can confirm the singular issue. :-P

**Comment by bhaettasch** [comment]
Closed by da3ba5382303796bd7869278e6ddb4dc7275fc11
