### ISSUE TITLE
Dress Size Overview: AttributeError

### ISSUE THREAD

**Issue by exploide** [d120/pyophase#43]
In production, the recently introduced dress size overview page triggers an
```
AttributeError at /admin/staff/person/
'NoneType' object has no attribute 'id'
```

Problem seems to be in the line `if person.dress_size.id == size.id:` Maybe one of the persons has no dress size.

Either @chriswars  knows what the problem is or I will have a look on it soon.

**Comment by chriswars** [comment]
I will fix this tomorrow
