### ISSUE TITLE
Use direct pdf export for certificates

### ISSUE THREAD

**Issue by bhaettasch** [d120/pyophase#45]
Currently, the export function creates a list of latex commands that can be used to create the real certificates.

It would be nice to produce these certificates directly inside the browser without the need to copy exported lines to a latex environment.

**Comment by bhaettasch** [comment]
This function should be available for individual freshman via admin interface and as mass action for all stundents using the dashboard.

**Comment by jlauinger** [comment]
fixed with #111

**Comment by ckleemann** [comment]
Also on dashboard/students/certificate the direct pdf generation should be used. I think the dashboard should be the default way to generate all certificates plus some blank once while the admin action should be the way to generate some certificates on demand.

**Comment by bhaettasch** [comment]
I mostly agree with @ckleemann -- I personally don't see the need for blank certificates, but the rest sounds reasonable.
