### ISSUE TITLE
Kleingruppen mit ≠ 2 Tutoren

### ISSUE THREAD

**Issue by max-weller** [d120/pyophase#46]
Der tex-Export exportiert nur die ersten zwei Tutoren

**Comment by ckleemann** [comment]
The code is hard-wired to exact 2 Tutors. But the latex file which consumes the data also supports only exact 2 Tutors.

**Comment by max-weller** [comment]
Then we should probably fix both of them...

**Comment by bhaettasch** [comment]
This behavior should change when using direct pdf export as described in #45.

**Comment by jlauinger** [comment]
fixed with #111
