### ISSUE TITLE
deletion of static contents

### ISSUE THREAD

**Issue by pollti** [d120/pyophase#463]
All static contents should probably be obsolete by now, as they are integrated in d120.de/ophase and can be removed.
For details, currently: Jonas, Jenny

**Comment by miterion** [comment]
Sounds like a good idea, can I assign you @pollti ?

**Comment by pollti** [comment]
I probably won't have the time for it before the next Ophase. I just opened this on demand of the new Leitung and winter website organizer :D

**Comment by miterion** [comment]
There is already a PR for this (#263), so maybe you can convince @jlauinger or someone else to finish the work over there.
