### ISSUE TITLE
"Aktueller Eintragungsstand" shows False for certain groups

### ISSUE THREAD

**Issue by exploide** [d120/pyophase#47]
On the dashboard page `dashboard/students/` ("Aktueller Eintragungsstand"), certain groups are listed along with a False entry in the "# Klausur" column.

**Comment by ckleemann** [comment]
I tried to reproduce this bug locale with a sqlite database. With sqlite the bug dose not exist. 

It looks like this is a bug in @django together with MySQL as database see https://code.djangoproject.com/ticket/24662

**Comment by ckleemann** [comment]
@exploide could you please verify that the bug is now fixed for the MySQL backend?

**Comment by exploide** [comment]
works for me
