### ISSUE TITLE
Prepopulate students fields?

### ISSUE THREAD

**Issue by bhaettasch** [d120/pyophase#48]
Lets continue our offline brainstorming here:

One way to speed up the registration process would be to prepopulate the table with a name list of applicants. Using an unique id that is also on the name tag of the student, he can flag his entry as active and edit his record (primarily decide if he wants to take the exam and what newsletter to subscribe to (if any)).

Some details for the process:
* The id could be scanned using a handheld barcode scanner
* A significant speedup can only be reached, if the e-mail field is already prepopulated (for example by data gained from university contact lists) - nevertheless, we have to make sure we only save neccessary data, so maybe it would also possible to lookup the e-mail adress on the fly
* Distributing students to groups, creating the list and getting additional information do not have to be part of pyophase, it should be sufficient to provide an import interface for that

This approach should also solve the problem with duplicates (see #44)

**Comment by exploide** [comment]
We should not load personal data from other sources into the application. Currently pressing the submit button implies that the person is okay with the fact that we use the information for the given purpose. There is no consent if we do it that differently.

**Comment by ckleemann** [comment]
Since there is no legal way to prepopulate students fields, this issue is a won't fix.
