### ISSUE TITLE
Link Jobs with Groupcategories

### ISSUE THREAD

**Issue by bhaettasch** [d120/pyophase#56]
Some jobs are only needed if there are groups of one or multiple specific categories. It would be nice to hide these jobs if none of those categories is active.

This consists of two parts:

- [x] Linking the models of job and group category with a ManyToMany relation (while using None as default for a job belonging to all categories without the need to explicitly model this)
- [x]  Hiding all jobs that are not universal and do not belong to any of the active categories

**Comment by exploide** [comment]
see also the notes in #70

**Comment by chriswars** [comment]
Bitte dran denken dass im Laufe einer ophase gruppenkategorien auch abselektiert werden wenn genügend Tutoren vorhanden sind. Genügend Bachelor Tutoren zu haben geht aber nicht damit einher genug Geländespielhelfer zu haben etc

**Comment by bhaettasch** [comment]
WIP: See PR #129
