### ISSUE TITLE
Cannot change settings objects (in admin interface)

### ISSUE THREAD

**Issue by bhaettasch** [d120/pyophase#57]
Trying to edit the settings objects (custom singletons) for staff as well as students, results in an Server Error (500). This also applies to deleting.

**Comment by bhaettasch** [comment]
Looks like the reason are the admin template changes introduced in django 1.9.

With debug information turned on, you get
`TypeError at /admin/staff/settings/1/change/
__str__ returned non-string (type __proxy__)`

The line
`&rsaquo; {% if add %}{% trans 'Add' %} {{ opts.verbose_name }}{% else %}{{ original|truncatewords:"18" }}{% endif %}`
seems to cause the error, probably because the filter in this line tries to truncate a translatable string.

**Comment by ckleemann** [comment]
ugettext_lazy dose not return a element of type __string__ but of type __proxy__ which let the truncate method of django_template fail.
@exploide: Is there a reason for the get_name method? I think it would be better to merge this into the  __str__ method.

**Comment by exploide** [comment]
I'm not sure, maybe this function is used automatically by the admin module. As far as I remember @bhaettasch added some of the `get_name` functions in favor of `str`.

**Comment by bhaettasch** [comment]
I am not totally sure, but as far as I remember the purpose was to allow showing the full name of the object as well as additional columns in the admin interface (and `str` then also uses those `get_name` methods to avoid code duplications).
