### ISSUE TITLE
Improved dress size form (& improved model)

### ISSUE THREAD

**Issue by bhaettasch** [d120/pyophase#58]
Instead of just asking for a dress size, it would be better to allow entering of more complex orders (also choose clothing kind/style, multiple clothing items, ...). Currently, the entered information is neither sufficient for ordering nor handing out.

Therefore, an improved model should be introduced that allows:
- [x] choosing multiple items (of different kinds)
- [ ] model whether these have already been payed and/or handed out
- [x] a simple export of summarized ordering lists
- [ ] displaying an overview list for handing out

**Comment by exploide** [comment]
It would be valuable to offer the clothing selection view independently from the staff registration view, since concrete properties of the clothing might become fixed much later than the registration period.

Maybe the payed and handed out facts can be stored in extra attributes for the relation (many to many?!). https://docs.djangoproject.com/en/dev/topics/db/models/#intermediary-manytomany

**Comment by bhaettasch** [comment]
Making this selection independent would require some kind of account handling, wouldn't it? While I think we should really consider this, the discussion for that should probably take place in a separate issue.

And yes, I am hoping that the facts can be stored as additional attributes in an intermediate many to many model.

**Comment by exploide** [comment]
Account handling is not necessarily mandatory, since the classical clothing selection using doodle polls isn't bound to accounts as well.

**Comment by bhaettasch** [comment]
Do you propose a model that is still bound to the model for registered people or completely independent?

**Comment by exploide** [comment]
I would propose some kind of relation between clothing and the already registered staff. Maybe a manytomany relation.

Of course, w/o an account system we need to rely on users acting trustworthy when selecting who they are.

An alternative would be to restructure everything and include the mentioned account system for staff. I guess this would be a very big change. Maybe we should eventually discuss this...
