### ISSUE TITLE
Mobile UI broken

### ISSUE THREAD

**Issue by ckleemann** [d120/pyophase#61]
There are several things in the Mobile
 UI which are broken on devices with 540x960 px screen size:
* The language selector uses the full device width
* There is no left padding for the content
* Text which belongs to the footer is below the footer.
![1](https://cloud.githubusercontent.com/assets/12739188/13913409/b3355752-ef46-11e5-8b78-b5be44fe1427.png)
![2](https://cloud.githubusercontent.com/assets/12739188/13913413/c185f3f2-ef46-11e5-9be7-681c2c3764f2.png)

**Comment by exploide** [comment]
* Language selector fixed
* padding not reproducible
* footer text still not fixed
