### ISSUE TITLE
Ophasebase countdown widget not properly translated

### ISSUE THREAD

**Issue by exploide** [d120/pyophase#62]
It seems that the translation of "x Tage bis zur Ophase" fails. Though the correct translation is listed in the mo file.

**Comment by ckleemann** [comment]
I can not reproduce this issue. In productive under English translation the message is _N Tage until the next Ophase_ which is the result of a wrong translation. I corrected that with 43362732f3fa296ffb6a58c9e96dd96edb14eb70.

Is there still a issue with it?

**Comment by exploide** [comment]
No, guess you are right. I missed that copy & waste issue.
