### ISSUE TITLE
Student registration decoupled from exam registration

### ISSUE THREAD

**Issue by bhaettasch** [d120/pyophase#63]
Currently, the student registrations main purpose is registering for the exam and additionally it is possible to subscribe to a newsletter, too.

While not all kinds of freshmen do have an exam, it would be nice to be able to use the registration nevertheless without the confusion why it is possible for them to register for an exam.

I am not completely sure how this could be archived in the best way, but probably the following changes/improvements would be necessary:
- [ ] Make the available newsletter dependent of the selected group (which belongs to a category)
- [x] Mark group categories where an exam takes place (additional boolean field?)
- [x] Change texts (view not called exam registration & newsletter section not called optional anymore)

**Comment by ckleemann** [comment]
I just created another url to the register view where the exam checkbox is missing and changed the text.

Are there any newsletters which are only addressed to some category and the subscription should be done via pyophase?

**Comment by bhaettasch** [comment]
In the last years, we collected mail addresses of international students seperately to send them additional information. In addtion, we had a special mailing list for bachelor freshmen after the reacreddition -- so yeah, there exist some cases where newsletters do only belong to a special group. 

But since we need this kind of abstract functionality for multiple functions, it would probably be the best to put this into its own issue with ophase-future-milestone before. Then this issue can be closed.

**Comment by ckleemann** [comment]
The main Problem is that a GroupCategory only has a label and no semantic in it. So it would require adding semantic to the GroupCategory. I will write a follow up issue
