### ISSUE TITLE
Staff & group detail views as part of the dashboard

### ISSUE THREAD

**Issue by bhaettasch** [d120/pyophase#64]
It would be nice to have some detailled staff and group overview informations on the dashboard, for example
- [x] how many tutors registered for each category
- [x] a list of groups (divided by categories)
- [x] overview tables for orgas (sorted by the jobs they do)

Of course these views must be protected in a way that it can only be seen by logged in persons with sufficient permissions.

**Comment by jlauinger** [comment]
Third bullet point is added with 1b536bb as an admin action for staff.

**Comment by bhaettasch** [comment]
First and third point are implemented with ef6e10d, group overview already exists on the tutor paring page. Nevertheless, the overview documents for the helpdesk containing the list of groups with their tutors, rooms and phone numbers should be included in the nametag export #103
