### ISSUE TITLE
Helfer/Orga/Tutoren Feld um gesetzt ergänzen

### ISSUE THREAD

**Issue by chriswars** [d120/pyophase#66]
Das manytomany Feld sollte nicht nur zwischen "nicht gewählt" und "gewählt" unterscheiden sondern auch "gesetzt" kennen für die Leute, die für die Aufgabe letztendlich auch ausgewählt wurden

**Comment by exploide** [comment]
Aus Gründen der Einfachheit einfach von der Leitung die tatsächlichen Dinge anwählen lassen genügt nicht?

**Comment by chriswars** [comment]
Darunter kann ich mir grade nichts vorstellen, kannst du näher beschreiben wie du das meinst?

**Comment by exploide** [comment]
Du meinst doch die Liste der Jobs für die sich Personen interessieren, oder? Da kann die Leitung dann die wieder rausnehmen für die die Person nicht eingesetzt wird.

**Comment by chriswars** [comment]
Ah, jetzt verstehe ich was du meinst

Das ist zwar theoretisch möglich, jedoch ist es (insbesondere bei den Helfern) immer gut zu wissen wer nachrücken könnte, wenn jemand aus welchem Grund auch immer ausfällt.
Bei dieser Lösung hätten wir dahingehend einen Informationsverlust den man mit der im Ticket genannten Lösung vermeiden könnte

**Comment by exploide** [comment]
Bei den Orga- und Helferjobs sollte das durch eine weitere Relation für die Person einfach zu ergänzen sein. Bei `tutor_for` sieht das anders aus, da dieses Feld aktuell ein einzelner `ForeignKey` ist, was in dieser Form nicht als Liste nutzbar ist. Entweder verzichtet man bei Tutoren auf die Funktionalität, oder man muss komplett ändern wie die Tutorenkategorie der Person gespeichert wird.

**Comment by chriswars** [comment]
Ich denke bei Tutoren kann man darauf verzichten. In der Praxis wird jeder der sich gemeldet hat auch Tutor während bei den Helfern und Orgas eher die "gib mal an woran du alles Interesse hättest, wir teilen dich dann zu" Schiene durch Leitung bzw helferorga gefahren wird

**Comment by bhaettasch** [comment]
Implemented with #175
