### ISSUE TITLE
remove style-tags from templates

### ISSUE THREAD

**Issue by ckleemann** [d120/pyophase#89]
With the new layout style definitions where set in some templates. The styling should happen outside the template

**Comment by jlauinger** [comment]
closed with b098b3ef5b09d2a8bcd52f2b3a180deb2212a75a

Among other things, using the boxes style primitive from the homepage is now a simple

```html
<div class="box box-highlight box-yellow">
    <h2>...</h2>
    <p>...</p>
</div>
```
