### ISSUE TITLE
Add unit testing for clothing app

### ISSUE THREAD

**Issue by jlauinger** [d120/pyophase#91]
Currently, the clothing app is untested. You know what to do.

**Comment by jlauinger** [comment]
Clothing models are 95% tested with f32dd320c3326afcc4b279d3f4b44639c790ad58

**Comment by ckleemann** [comment]
What is about TestCases for the Views?

**Comment by bhaettasch** [comment]
Now that clothing uses django standard views (create, update, delete) instead of a complicated multistep form, creating tests for the views would be a waste of time. Hence I'm closing this issue now.
