### ISSUE TITLE
Fehler bei fehlendem Stundenplan abfangen

### ISSUE THREAD

**Issue by chriswars** [d120/pyophase#95]
Für den Fall, dass kein Stundenplan für einen Typ Ophase hinterlegt ist, sollte keine Exception fliegen sondern die normale Seite mit der Meldung "Der Stundenplan für diese Ophase ist derzeit noch nicht verfügbar." anstelle der Grafik anzeigen.

- [x] Bachelor
- [x] Master
- [ ] Master DSS
- [ ] Lehramt
- [ ] JBA

**Comment by bhaettasch** [comment]
This was implemented for bachelor with 51fb2419ca26676bd4f08dc698720b791803b569 but has to be done individually for all the detail pages:

- [ ] Bachelor
- [ ] Master
- [ ] Master DSS
- [ ] Lehramt
- [ ] JBA

**Comment by bhaettasch** [comment]
Added check for master detail page with 730e429

**Comment by ckleemann** [comment]
Wont Fix. The content app is deprecated and will be removed as requested in #463
